name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    services:
      # Using SQLite3 for integration tests throws `django.db.utils.OperationalError: database table is locked: workbench_xblockstate`.
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpw
        ports:
          - 3307:3306
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
        toxenv: [django32, django42, integration-django32, integration-django42, quality-django32, quality-django42, translations-django32, translations-django42]

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # `libgtk2.0-0` and `libxt6` are required by an older version of Firefox.
    - name: Install Required System Packages
      if: matrix.toxenv == 'integration'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev ubuntu-restricted-extras xvfb libxml2-dev libxslt-dev libevent-dev libgtk2.0-0 libxt6

    - name: Install translations dependencies
      if: matrix.toxenv == 'translations'
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext

    - name: Install Dependencies
      run: make requirements

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
